#!/usr/bin/env python3
"""NanamiCat puzzle generator – adds groups + entries to reach 100 per difficulty (zh)."""
import json
from collections import Counter

ZH_PATH = '/Users/zdh/Developer/web/nanamicat/public/puzzle-data.json'

with open(ZH_PATH) as f:
    data = json.load(f)

existing_bank     = list(data['textGroupBank'])
existing_manifest = list(data['textPuzzleManifest'])
existing_ids      = {g['id'] for g in existing_bank}

# ── NEW GROUPS ───────────────────────────────────────────────────────────
# Groups are dicts; words lists must be exactly 4 unique items.

NEW_GROUPS = [
# ── L1 (40 groups) ──────────────────────────────────────────────────────
{"id":"pets",               "level":1,"name":"常见宠物",  "words":["猫","狗","金鱼","仓鼠"]},
{"id":"playground",         "level":1,"name":"游乐设施",  "words":["秋千","滑梯","跷跷板","沙坑"]},
{"id":"rain-gear",          "level":1,"name":"雨天用品",  "words":["雨伞","雨衣","雨靴","防水袋"]},
{"id":"spring-customs",     "level":1,"name":"春节习俗",  "words":["贴春联","放烟花","拜年","发红包"]},
{"id":"board-games-zh",     "level":1,"name":"棋类游戏",  "words":["跳棋","飞行棋","五子棋","斗兽棋"]},
{"id":"summer-drinks",      "level":1,"name":"夏日冷饮",  "words":["柠檬水","椰奶","刨冰","西瓜汁"]},
{"id":"cleaning-supplies",  "level":1,"name":"清洁用品",  "words":["洗碗液","洗衣粉","漂白水","消毒液"]},
{"id":"indoor-plants",      "level":1,"name":"室内植物",  "words":["仙人掌","绿萝","多肉","富贵竹"]},
{"id":"light-devices",      "level":1,"name":"照明器具",  "words":["手电筒","蜡烛","台灯","壁灯"]},
{"id":"dynasties-zh",       "level":1,"name":"历史朝代",  "words":["秦朝","汉朝","唐朝","宋朝"]},
{"id":"outdoor-sports",     "level":1,"name":"户外运动",  "words":["登山","徒步","露营","攀岩"]},
{"id":"fast-food-zh",       "level":1,"name":"快餐食品",  "words":["汉堡","薯条","炸鸡","热狗"]},
{"id":"noodle-types",       "level":1,"name":"面条种类",  "words":["刀削面","担担面","炸酱面","热干面"]},
{"id":"shapes-zh",          "level":1,"name":"几何图形",  "words":["三角形","正方形","椭圆形","六边形"]},
{"id":"trad-crafts",        "level":1,"name":"传统手工艺","words":["剪纸","刺绣","景泰蓝","木版年画"]},
{"id":"lit-genres",         "level":1,"name":"文学体裁",  "words":["诗歌","小说","散文","剧本"]},
{"id":"med-items",          "level":1,"name":"医疗用品",  "words":["绷带","体温表","棉签","创可贴"]},
{"id":"measure-tools",      "level":1,"name":"测量工具",  "words":["温度计","台秤","量杯","卷尺"]},
{"id":"famous-dishes",      "level":1,"name":"中华名菜",  "words":["北京烤鸭","东坡肉","夫妻肺片","宫保鸡丁"]},
{"id":"id-docs",            "level":1,"name":"证件类型",  "words":["身份证","学生证","工作证","驾驶证"]},
{"id":"snacks-zh",          "level":1,"name":"休闲零食",  "words":["薯片","爆米花","饼干","棒棒糖"]},
{"id":"western-pastries",   "level":1,"name":"西式糕点",  "words":["蛋糕","面包","曲奇","可颂"]},
{"id":"art-types",          "level":1,"name":"艺术门类",  "words":["绘画","雕塑","书法","摄影"]},
{"id":"chinese-opera-types","level":1,"name":"地方戏曲",  "words":["京剧","越剧","黄梅戏","粤剧"]},
{"id":"four-inventions",    "level":1,"name":"四大发明",  "words":["造纸术","印刷术","火药","指南针"]},
{"id":"new-year-food",      "level":1,"name":"年节食品",  "words":["饺子","年糕","汤圆","腊八粥"]},
{"id":"calligraphy-styles", "level":1,"name":"书法字体",  "words":["楷书","行书","草书","隶书"]},
{"id":"film-genres-zh",     "level":1,"name":"电影类型",  "words":["喜剧片","恐怖片","动作片","爱情片"]},
{"id":"province-capitals",  "level":1,"name":"省会城市",  "words":["杭州","南京","西安","武汉"]},
{"id":"solar-terms-zh",     "level":1,"name":"节气",      "words":["立春","谷雨","冬至","大暑"]},
{"id":"ancient-weapons",    "level":1,"name":"古代兵器",  "words":["长刀","长剑","弓箭","长矛"]},
{"id":"house-rooms",        "level":1,"name":"居室空间",  "words":["客厅","卧室","厨房","浴室"]},
{"id":"fish-gear",          "level":1,"name":"钓鱼用品",  "words":["鱼竿","鱼线","鱼钩","渔网"]},
{"id":"ink-tools",          "level":1,"name":"绘画材料",  "words":["水彩","油彩","炭笔","水墨"]},
{"id":"porridge-types",     "level":1,"name":"粥品种类",  "words":["白粥","皮蛋粥","八宝粥","小米粥"]},
{"id":"team-ball-sports",   "level":1,"name":"团队球类",  "words":["排球","曲棍球","棒球","橄榄球"]},
{"id":"mythical-beasts",    "level":1,"name":"神话瑞兽",  "words":["龙","凤凰","麒麟","貔貅"]},
{"id":"folk-instruments",   "level":1,"name":"民族乐器",  "words":["二胡","琵琶","唢呐","古筝"]},
{"id":"body-organs",        "level":1,"name":"内脏器官",  "words":["心脏","肝脏","肾脏","肺脏"]},
{"id":"camping-gear",       "level":1,"name":"露营装备",  "words":["帐篷","睡袋","炉具","头灯"]},
# ── L2 (50 groups) ──────────────────────────────────────────────────────
{"id":"job-interview",      "level":2,"name":"面试环节",  "words":["投递","初试","复试","录用"]},
{"id":"cooking-prep",       "level":2,"name":"备菜流程",  "words":["选材","清洗","切配","腌制"]},
{"id":"moving-home",        "level":2,"name":"搬家流程",  "words":["打包","装车","卸货","整理"]},
{"id":"book-publishing",    "level":2,"name":"出书流程",  "words":["约稿","初审","修改","定稿"]},
{"id":"app-launch",         "level":2,"name":"软件发版",  "words":["需求","开发","测试","上线"]},
{"id":"wedding-plan",       "level":2,"name":"婚礼筹备",  "words":["订场","拟帖","彩排","典礼"]},
{"id":"loan-steps",         "level":2,"name":"贷款流程",  "words":["申请","审核","放款","还款"]},
{"id":"cake-baking",        "level":2,"name":"烤蛋糕",    "words":["打蛋","拌粉","倒模","烤制"]},
{"id":"surgery-stages",     "level":2,"name":"手术过程",  "words":["消毒","切开","缝合","苏醒"]},
{"id":"academic-research",  "level":2,"name":"学术研究",  "words":["确题","综述","实验","发表"]},
{"id":"photo-shooting",     "level":2,"name":"摄影修图",  "words":["构图","曝光","对焦","后期"]},
{"id":"housing-buy",        "level":2,"name":"购房步骤",  "words":["看房","谈价","签约","过户"]},
{"id":"court-trial",        "level":2,"name":"庭审环节",  "words":["开庭","举证","辩论","宣判"]},
{"id":"vote-process",      "level":2,"name":"选举流程",  "words":["提名","拉票","投票","计票"]},
{"id":"hospital-visit",     "level":2,"name":"就医流程",  "words":["挂号","候诊","问诊","取药"]},
{"id":"garden-care",        "level":2,"name":"养花步骤",  "words":["选苗","栽种","施肥","修剪"]},
{"id":"restaurant-service", "level":2,"name":"餐厅服务",  "words":["迎客","点单","上菜","结账"]},
{"id":"laundry-steps",      "level":2,"name":"洗衣流程",  "words":["分拣","浸泡","搓洗","晾晒"]},
{"id":"pet-bathing",        "level":2,"name":"给宠物洗澡","words":["湿毛","涂洗毛精","冲洗","吹干"]},
{"id":"travel-booking",     "level":2,"name":"出行预订",  "words":["选目的地","订机票","订酒店","规划行程"]},
{"id":"car-maintenance",    "level":2,"name":"汽车保养",  "words":["换机油","查刹车","充轮胎","清滤网"]},
{"id":"exam-prep",          "level":2,"name":"考试准备",  "words":["报名","复习","模拟","答卷"]},
{"id":"seedling-grow",      "level":2,"name":"育苗过程",  "words":["播种","发芽","移植","成株"]},
{"id":"film-production",    "level":2,"name":"电影制作",  "words":["选角","布景","收音","剪接"]},
{"id":"news-report",        "level":2,"name":"新闻采编",  "words":["选题","采访","撰稿","审稿"]},
{"id":"email-etiquette",    "level":2,"name":"写正式邮件","words":["称呼","正文","附件","签名"]},
{"id":"training-cycle",     "level":2,"name":"培训环节",  "words":["入学","学习","实习","结业"]},
{"id":"budget-plan",        "level":2,"name":"预算管理",  "words":["估算","分配","执行","复盘"]},
{"id":"customer-service",   "level":2,"name":"客服流程",  "words":["接单","核实","处理","回访"]},
{"id":"brand-launch",       "level":2,"name":"品牌发布",  "words":["调研","策划","设计","推广"]},
{"id":"food-delivery",      "level":2,"name":"外卖点单",  "words":["浏览","选菜","付款","等待"]},
{"id":"fire-response",      "level":2,"name":"火灾应对",  "words":["发现","报警","疏散","灭火"]},
{"id":"negotiation-flow",   "level":2,"name":"谈判步骤",  "words":["开场","亮牌","讨价","握手"]},
{"id":"project-manage",     "level":2,"name":"项目管理",  "words":["立项","计划","推进","交付"]},
{"id":"warehouse-ops",      "level":2,"name":"仓储操作",  "words":["入库","盘点","拣货","出库"]},
{"id":"legal-contract",     "level":2,"name":"合同签署",  "words":["起草","审阅","谈判","盖章"]},
{"id":"school-admission",   "level":2,"name":"大学招生",  "words":["报考","笔试","面试","录取"]},
{"id":"audit-steps",        "level":2,"name":"财务审计",  "words":["取证","核对","评估","出报告"]},
{"id":"product-recall",     "level":2,"name":"产品召回",  "words":["检测","公告","回收","赔偿"]},
{"id":"social-post",        "level":2,"name":"社交发帖",  "words":["滤镜","配文","发布","互动"]},
{"id":"spring-cleaning",    "level":2,"name":"年底大扫除","words":["清空","擦拭","归位","丢弃"]},
{"id":"reunion-dinner",     "level":2,"name":"年夜饭准备","words":["采购","备菜","掌厨","上桌"]},
{"id":"diploma-steps",      "level":2,"name":"毕业论文",  "words":["开题","写作","答辩","修订"]},
{"id":"immigration-flow",   "level":2,"name":"出国手续",  "words":["申请签证","办护照","托运","入境"]},
{"id":"podcast-make",       "level":2,"name":"制作播客",  "words":["录音","剪辑","上传","运营"]},
{"id":"art-exhibition",     "level":2,"name":"办画展",    "words":["选作品","布置","开幕","撤展"]},
{"id":"crisis-manage",      "level":2,"name":"危机公关",  "words":["监测","澄清","声明","善后"]},
{"id":"marathon-day",       "level":2,"name":"马拉松当天","words":["热身","起跑","补给","冲线"]},
{"id":"novel-writing",      "level":2,"name":"写小说",    "words":["大纲","起稿","润色","投稿"]},
{"id":"diy-repair",         "level":2,"name":"居家维修",  "words":["排查","购材","施工","修缮"]},
# ── L3 (40 groups) ──────────────────────────────────────────────────────
{"id":"invisible-cost",     "level":3,"name":"无形成本",    "words":["时间","信任","注意力","机会"]},
{"id":"threshold-states",   "level":3,"name":"临界状态",    "words":["沸点","冰点","极限","边界"]},
{"id":"delayed-effect",     "level":3,"name":"延迟效应",    "words":["余震","后劲","回声","余温"]},
{"id":"proxy-as-original",  "level":3,"name":"以代理代替本体","words":["地图","菜单","简历","预告片"]},
{"id":"compressed-info",    "level":3,"name":"压缩信息",    "words":["标题","摘要","徽标","二维码"]},
{"id":"feedback-loop",      "level":3,"name":"正反馈循环",  "words":["滚雪球","马太效应","增强回路","复利"]},
{"id":"bottleneck",         "level":3,"name":"瓶颈",        "words":["单线程","独木桥","卡脖子","限流阀"]},
{"id":"emergence",          "level":3,"name":"涌现现象",    "words":["蚁群","舆论","市场","集体意识"]},
{"id":"anchor-bias",        "level":3,"name":"锚定效应",    "words":["定价参考","初印象","第一稿","起点"]},
{"id":"translation-loss",   "level":3,"name":"转化损耗",    "words":["翻译","改编","简化","执行落差"]},
{"id":"scale-change",       "level":3,"name":"规模变换",    "words":["微观","宏观","放大","聚合"]},
{"id":"inversion-trap",     "level":3,"name":"反转陷阱",    "words":["过度优化","倒退","失控","报复性反弹"]},
{"id":"second-order-effect","level":3,"name":"二阶效应",    "words":["副作用","连锁反应","蝴蝶效应","间接损耗"]},
{"id":"context-collapse",   "level":3,"name":"语境塌陷",    "words":["断章取义","截图","去语境","迁移"]},
{"id":"invisible-rules",    "level":3,"name":"隐性规则",    "words":["潜规则","行规","默契","惯例"]},
{"id":"necessary-waste",    "level":3,"name":"必要冗余",    "words":["备份","安全边际","保险","冗余设计"]},
{"id":"signal-noise",       "level":3,"name":"信号与噪音",  "words":["过滤","筛选","聚焦","屏蔽"]},
{"id":"momentum",           "level":3,"name":"势头效应",    "words":["惯性","趋势","风口","积累"]},
{"id":"reversal-of-means",  "level":3,"name":"手段目的化",  "words":["KPI崇拜","形式主义","过度量化","指标异化"]},
{"id":"blind-spot",         "level":3,"name":"盲点",        "words":["忽视","定势","偏见","默认值"]},
{"id":"path-dependency",    "level":3,"name":"路径依赖",    "words":["沉没成本","轨道锁定","历史包袱","固化"]},
{"id":"abstraction-ladder", "level":3,"name":"抽象层级",    "words":["具体","概念","原则","公理"]},
{"id":"false-dichotomy",    "level":3,"name":"伪二元对立",  "words":["非此即彼","极端化","中间地带","灰度"]},
{"id":"time-discount",      "level":3,"name":"时间折现",    "words":["急功近利","短视","及时满足","未来贴现"]},
{"id":"narrative-control",  "level":3,"name":"叙事控制",    "words":["定性","框架","议程设置","话语权"]},
{"id":"legitimacy-sources", "level":3,"name":"合法性来源",  "words":["权威","传统","程序","共识"]},
{"id":"counterfactual",     "level":3,"name":"反事实推断",  "words":["如果当初","假设","情景模拟","对照组"]},
{"id":"commons-dilemma",    "level":3,"name":"公地悲剧",    "words":["过度开采","搭便车","外部性","集体行动失灵"]},
{"id":"granularity",        "level":3,"name":"粒度差异",    "words":["像素","条款细节","字体","毛细血管"]},
{"id":"local-vs-global",    "level":3,"name":"局部与全局",  "words":["局部极值","视野局限","协调失败","最优解"]},
{"id":"abstraction-cost",   "level":3,"name":"抽象代价",    "words":["泛化","失真","过度简化","模型误差"]},
{"id":"expectation-gap",    "level":3,"name":"期望落差",    "words":["幻灭感","过度承诺","理想化","现实校准"]},
{"id":"contagion",          "level":3,"name":"蔓延效应",    "words":["传染","情绪感染","流行文化","病毒传播"]},
{"id":"map-territory",      "level":3,"name":"地图与领土",  "words":["模型","仿真","简化图","抽象化"]},
{"id":"sunk-cost-mirror",   "level":3,"name":"沉没成本幻觉","words":["坚持错误","合理化","越投越舍不得","损失厌恶"]},
{"id":"coordination",       "level":3,"name":"协调问题",    "words":["标准化","公约","预期对齐","共同知识"]},
{"id":"selection-bias",     "level":3,"name":"选择性偏差",  "words":["幸存者偏差","样本偏差","确认偏误","可得性偏见"]},
{"id":"hierarchy-costs",    "level":3,"name":"层级代价",    "words":["信息衰减","官僚滞后","执行变形","传话失真"]},
{"id":"leaky-abstraction",  "level":3,"name":"泄漏的抽象",  "words":["细节渗出","底层暴露","封装失效","假装不知道"]},
{"id":"identity-vs-role",   "level":3,"name":"身份与角色",  "words":["演员","卧底","化名","职务"]},
]

# ── MANIFEST ENTRIES ─────────────────────────────────────────────────────
# Each entry is a list: [difficulty, theme, redHerring, [g0, g1, g2, g3]]
# Slot order: g0=yellow(easy), g1=green, g2=blue, g3=purple(abstract)

D1 = [
    [1,"日常起居","注意：一个词是动作，其余是物品。",
     ["house-rooms","job-interview","delayed-effect","reversal-of-means"]],
    [1,"一日三餐","注意：一个词是烹饪步骤而非食物。",
     ["porridge-types","cooking-prep","invisible-cost","path-dependency"]],
    [1,"节日里的中国","注意：一个词是情感而非活动。",
     ["spring-customs","new-year-food","contagion","legitimacy-sources"]],
    [1,"雨天出门","注意：一个词描述感受而非物品。",
     ["rain-gear","hospital-visit","threshold-states","narrative-control"]],
    [1,"文艺爱好","注意：一个词是流程而非艺术门类。",
     ["art-types","art-exhibition","feedback-loop","anchor-bias"]],
    [1,"厨房探险","注意：一个词是食材处理步骤。",
     ["famous-dishes","cooking-prep","abstraction-ladder","selection-bias"]],
    [1,"出行前准备","注意：一个词是文件而非行动。",
     ["id-docs","travel-booking","compressed-info","time-discount"]],
    [1,"运动场上","注意：一个词是规则而非动作。",
     ["team-ball-sports","marathon-day","bottleneck","coordination"]],
    [1,"文化符号","注意：一个词是概念而非具体事物。",
     ["four-inventions","chinese-opera-types","invisible-rules","hierarchy-costs"]],
    [1,"家的细节","注意：一个词是感觉而非实物。",
     ["indoor-plants","light-devices","signal-noise","expectation-gap"]],
    [1,"一年时光","注意：一个词是周期而非物品。",
     ["solar-terms-zh","camping-gear","delayed-effect","false-dichotomy"]],
    [1,"孩子的世界","注意：一个词是规则而非玩具。",
     ["playground","board-games-zh","invisible-rules","sunk-cost-mirror"]],
    [1,"现代健康","注意：一个词是流程而非物品。",
     ["med-items","body-organs","translation-loss","granularity"]],
    [1,"文字的力量","注意：一个词是载体而非文字本身。",
     ["calligraphy-styles","lit-genres","proxy-as-original","emergence"]],
    [1,"饮食文化","注意：一个词是食物加工过程。",
     ["noodle-types","famous-dishes","anchor-bias","legitimacy-sources"]],
]

D2 = [
    [2,"工作里的仪式","注意：一个词描述结果而非过程。",
     ["job-interview","project-manage","invisible-rules","reversal-of-means"]],
    [2,"从零到一","注意：一个词是抽象阶段而非实体动作。",
     ["app-launch","brand-launch","abstraction-ladder","emergence"]],
    [2,"合法性与规则","注意：一个词是权力符号。",
     ["legal-contract","court-trial","legitimacy-sources","narrative-control"]],
    [2,"准备迎接","注意：一个词是心理状态而非行动。",
     ["exam-prep","wedding-plan","expectation-gap","time-discount"]],
    [2,"生长的秘密","注意：一个词是条件而非步骤。",
     ["seedling-grow","garden-care","feedback-loop","delayed-effect"]],
    [2,"房子与家","注意：一个词是情感而非物理空间。",
     ["housing-buy","house-rooms","path-dependency","invisible-cost"]],
    [2,"钱的流动","注意：一个词是心理效应而非金融操作。",
     ["loan-steps","budget-plan","anchor-bias","sunk-cost-mirror"]],
    [2,"信息怎么传","注意：一个词是失真现象而非媒介。",
     ["news-report","social-post","translation-loss","hierarchy-costs"]],
    [2,"出国的手续","注意：一个词是文件而非动作。",
     ["immigration-flow","travel-booking","compressed-info","legitimacy-sources"]],
    [2,"身体的修复","注意：一个词是恢复过程而非药品。",
     ["surgery-stages","hospital-visit","delayed-effect","threshold-states"]],
    [2,"事件的连锁","注意：一个词是结构现象而非具体事件。",
     ["fire-response","crisis-manage","contagion","second-order-effect"]],
    [2,"学问的边界","注意：一个词是知识谬误而非研究步骤。",
     ["academic-research","diploma-steps","selection-bias","false-dichotomy"]],
    [2,"品牌与市场","注意：一个词是心理偏见而非市场行为。",
     ["brand-launch","customer-service","anchor-bias","narrative-control"]],
    [2,"制造热度","注意：一个词是社会现象而非媒体操作。",
     ["podcast-make","social-post","contagion","feedback-loop"]],
    [2,"资产与风险","注意：一个词是心理倾向而非资产类型。",
     ["audit-steps","product-recall","necessary-waste","time-discount"]],
    [2,"数字世界","注意：一个词是系统缺陷而非功能。",
     ["app-launch","food-delivery","leaky-abstraction","bottleneck"]],
    [2,"烹饪的哲学","注意：一个词是烹饪步骤隐喻。",
     ["cooking-prep","cake-baking","abstraction-ladder","proxy-as-original"]],
    [2,"对话与谈判","注意：一个词是博弈策略而非沟通方式。",
     ["negotiation-flow","customer-service","invisible-rules","coordination"]],
    [2,"艺术的生命","注意：一个词是创作障碍而非艺术形式。",
     ["art-exhibition","film-production","expectation-gap","reversal-of-means"]],
    [2,"时间的管理","注意：一个词是偏见而非时间管理工具。",
     ["marathon-day","project-manage","time-discount","path-dependency"]],
    [2,"动植物的生长","注意：一个词是生长失败模式。",
     ["seedling-grow","garden-care","bottleneck","contagion"]],
    [2,"信任建立","注意：一个词是信任危机而非建立方式。",
     ["wedding-plan","legal-contract","invisible-cost","legitimacy-sources"]],
    [2,"预期管理","注意：一个词描述落差而非预期本身。",
     ["training-cycle","school-admission","expectation-gap","anchor-bias"]],
    [2,"简与繁","注意：一个词是简化带来的代价。",
     ["calligraphy-styles","book-publishing","abstraction-cost","translation-loss"]],
    [2,"仪式与过程","注意：一个词是仪式的隐含功能而非步骤。",
     ["reunion-dinner","spring-cleaning","invisible-rules","legitimacy-sources"]],
    [2,"知识的管理","注意：一个词是信息传播失真现象。",
     ["novel-writing","academic-research","hierarchy-costs","signal-noise"]],
    [2,"物流与仓储","注意：一个词是系统低效而非操作步骤。",
     ["warehouse-ops","food-delivery","bottleneck","coordination"]],
    [2,"照护他人","注意：一个词是情感消耗而非照护行动。",
     ["pet-bathing","hospital-visit","invisible-cost","expectation-gap"]],
    [2,"竞争格局","注意：一个词是策略误区而非竞争手段。",
     ["vote-process","negotiation-flow","false-dichotomy","selection-bias"]],
    [2,"创意生产","注意：一个词是创意陷阱而非创作步骤。",
     ["podcast-make","novel-writing","reversal-of-means","momentum"]],
    [2,"数字痕迹","注意：一个词是信息泄漏而非数字行为。",
     ["social-post","email-etiquette","context-collapse","leaky-abstraction"]],
    [2,"集体行为","注意：一个词是失灵机制而非集体行为类型。",
     ["reunion-dinner","marathon-day","commons-dilemma","coordination"]],
    [2,"质量管理","注意：一个词是质量陷阱而非控制手段。",
     ["product-recall","audit-steps","selection-bias","reversal-of-means"]],
    [2,"技艺与传承","注意：一个词是传承失真而非技艺本身。",
     ["trad-crafts","folk-instruments","translation-loss","path-dependency"]],
    [2,"危机与应对","注意：一个词是系统缺陷而非应对方式。",
     ["fire-response","crisis-manage","second-order-effect","blind-spot"]],
    [2,"模式的识别","注意：一个词是认知偏差而非模式本身。",
     ["board-games-zh","exam-prep","selection-bias","anchor-bias"]],
    [2,"服务体验","注意：一个词是期望管理的失败模式。",
     ["restaurant-service","customer-service","expectation-gap","context-collapse"]],
    [2,"建造与修缮","注意：一个词是施工陷阱而非步骤。",
     ["diy-repair","house-rooms","path-dependency","invisible-cost"]],
    [2,"符号与意义","注意：一个词是符号失效情形。",
     ["ancient-weapons","four-inventions","proxy-as-original","legitimacy-sources"]],
    [2,"结构与流程","注意：一个词是流程失效点。",
     ["laundry-steps","spring-cleaning","bottleneck","path-dependency"]],
    [2,"户外与自然","注意：一个词是风险而非活动。",
     ["outdoor-sports","camping-gear","threshold-states","delayed-effect"]],
    [2,"跨越边界","注意：一个词是边界消融效应。",
     ["immigration-flow","province-capitals","map-territory","context-collapse"]],
    [2,"节奏与停顿","注意：一个词是停顿的深层作用。",
     ["solar-terms-zh","marathon-day","momentum","delayed-effect"]],
    [2,"亮相与包装","注意：一个词是外包装的副作用。",
     ["western-pastries","brand-launch","compressed-info","anchor-bias"]],
    [2,"工具与目的","注意：一个词是工具目的化的现象。",
     ["measure-tools","fish-gear","reversal-of-means","leaky-abstraction"]],
    [2,"治理与秩序","注意：一个词是秩序失效机制。",
     ["court-trial","vote-process","legitimacy-sources","commons-dilemma"]],
    [2,"语言与表达","注意：一个词是语义扭曲现象。",
     ["lit-genres","news-report","context-collapse","translation-loss"]],
    [2,"现代城市","注意：一个词是城市运行陷阱。",
     ["province-capitals","restaurant-service","coordination","emergence"]],
]

D3 = [
    [3,"隐形代价","注意：一个词是有形损耗，其余是无形代价。",
     ["invisible-cost","necessary-waste","second-order-effect","reversal-of-means"]],
    [3,"信息的层次","注意：一个词是存储而非传递。",
     ["compressed-info","signal-noise","hierarchy-costs","abstraction-ladder"]],
    [3,"反馈与循环","注意：一个词是循环的终止而非维持。",
     ["feedback-loop","contagion","momentum","path-dependency"]],
    [3,"思维的陷阱","注意：一个词是正确启发法而非偏见。",
     ["selection-bias","anchor-bias","false-dichotomy","blind-spot"]],
    [3,"系统的边界","注意：一个词是边界渗透现象。",
     ["threshold-states","leaky-abstraction","map-territory","local-vs-global"]],
    [3,"语言的滑移","注意：一个词是语言精确化而非失真。",
     ["translation-loss","context-collapse","narrative-control","abstraction-cost"]],
    [3,"时间的力量","注意：一个词是时间加速而非延迟。",
     ["delayed-effect","time-discount","path-dependency","momentum"]],
    [3,"代理的局限","注意：一个词是代理恰当使用的案例。",
     ["proxy-as-original","map-territory","compressed-info","leaky-abstraction"]],
    [3,"集体与个体","注意：一个词是集体优于个体的情形。",
     ["emergence","commons-dilemma","coordination","contagion"]],
    [3,"规模的奥秘","注意：一个词是规模缩减效应。",
     ["scale-change","feedback-loop","local-vs-global","granularity"]],
    [3,"权力的形状","注意：一个词是权力自我瓦解的机制。",
     ["legitimacy-sources","narrative-control","hierarchy-costs","invisible-rules"]],
    [3,"期望的管理","注意：一个词是期望准确设定的方法。",
     ["expectation-gap","anchor-bias","time-discount","sunk-cost-mirror"]],
    [3,"决策的代价","注意：一个词是决策的不可逆性。",
     ["path-dependency","sunk-cost-mirror","false-dichotomy","counterfactual"]],
    [3,"可见与不可见","注意：一个词是主动可见而非隐藏。",
     ["invisible-cost","invisible-rules","blind-spot","signal-noise"]],
    [3,"抽象的成本","注意：一个词是抽象的正面价值。",
     ["abstraction-cost","abstraction-ladder","map-territory","translation-loss"]],
    [3,"规则的双刃","注意：一个词是规则恰当发挥作用的情形。",
     ["invisible-rules","legitimacy-sources","coordination","reversal-of-means"]],
    [3,"知识的边界","注意：一个词是知识扩展而非局限。",
     ["blind-spot","selection-bias","abstraction-cost","counterfactual"]],
    [3,"结构与动态","注意：一个词是纯静态结构而非动态。",
     ["bottleneck","momentum","delayed-effect","threshold-states"]],
    [3,"局部与整体","注意：一个词是协调成功而非失败。",
     ["local-vs-global","coordination","commons-dilemma","granularity"]],
    [3,"定义的力量","注意：一个词是定义被滥用的现象。",
     ["narrative-control","legitimacy-sources","false-dichotomy","proxy-as-original"]],
    [3,"测量的局限","注意：一个词是测量准确性的来源。",
     ["granularity","selection-bias","reversal-of-means","map-territory"]],
    [3,"改变的阻力","注意：一个词是变革成功的条件。",
     ["path-dependency","sunk-cost-mirror","inversion-trap","hierarchy-costs"]],
    [3,"过度的危险","注意：一个词是适度积累的正面效应。",
     ["inversion-trap","reversal-of-means","feedback-loop","anchor-bias"]],
    [3,"信任与欺骗","注意：一个词是信任破坏后的修复。",
     ["invisible-rules","legitimacy-sources","context-collapse","expectation-gap"]],
    [3,"压缩与还原","注意：一个词是还原的代价而非过程。",
     ["compressed-info","abstraction-cost","translation-loss","proxy-as-original"]],
    [3,"稳定的幻觉","注意：一个词是真实稳定的特征。",
     ["threshold-states","path-dependency","necessary-waste","coordination"]],
    [3,"连接的本质","注意：一个词是连接断裂的现象。",
     ["coordination","contagion","emergence","legitimacy-sources"]],
    [3,"数字镜像","注意：一个词是现实与镜像重合的情形。",
     ["map-territory","proxy-as-original","context-collapse","leaky-abstraction"]],
    [3,"资源与稀缺","注意：一个词是资源丰裕下的失灵。",
     ["commons-dilemma","invisible-cost","bottleneck","time-discount"]],
    [3,"逻辑的漏洞","注意：一个词是逻辑正确推理的特征。",
     ["false-dichotomy","selection-bias","anchor-bias","counterfactual"]],
    [3,"秩序与混沌","注意：一个词是自发秩序而非强制。",
     ["emergence","coordination","legitimacy-sources","invisible-rules"]],
    [3,"摩擦的价值","注意：一个词是摩擦有益的情形。",
     ["necessary-waste","threshold-states","delayed-effect","second-order-effect"]],
    [3,"现象的原因","注意：一个词是相关性而非因果性。",
     ["second-order-effect","contagion","feedback-loop","selection-bias"]],
    [3,"速度与质量","注意：一个词是速度提升的副作用。",
     ["bottleneck","momentum","inversion-trap","time-discount"]],
    [3,"符号的演变","注意：一个词是符号固化现象。",
     ["proxy-as-original","compressed-info","narrative-control","path-dependency"]],
    [3,"实验与假设","注意：一个词是假设检验的盲区。",
     ["counterfactual","selection-bias","blind-spot","abstraction-cost"]],
    [3,"精度与误差","注意：一个词是精度损耗的根本原因。",
     ["granularity","translation-loss","map-territory","leaky-abstraction"]],
    [3,"弱连接的力量","注意：一个词是强连接优势的体现。",
     ["contagion","emergence","coordination","hierarchy-costs"]],
    [3,"短期与长期","注意：一个词是牺牲短期正确的情形。",
     ["time-discount","delayed-effect","path-dependency","sunk-cost-mirror"]],
    [3,"自我欺骗","注意：一个词是避免自欺的方式。",
     ["sunk-cost-mirror","blind-spot","selection-bias","inversion-trap"]],
    [3,"文化的惰性","注意：一个词是文化快速变革的现象。",
     ["invisible-rules","path-dependency","legitimacy-sources","context-collapse"]],
    [3,"优化的边界","注意：一个词是真正最优的条件。",
     ["local-vs-global","inversion-trap","reversal-of-means","abstraction-cost"]],
    [3,"拥有与丧失","注意：一个词是损失的正面意义。",
     ["invisible-cost","sunk-cost-mirror","necessary-waste","threshold-states"]],
    [3,"数量的陷阱","注意：一个词是数量恰当衡量的情形。",
     ["granularity","selection-bias","false-dichotomy","reversal-of-means"]],
    [3,"边界的作用","注意：一个词是边界消融的益处。",
     ["threshold-states","coordination","local-vs-global","context-collapse"]],
    [3,"语义的漂移","注意：一个词是语义稳定的条件。",
     ["context-collapse","translation-loss","narrative-control","abstraction-cost"]],
    [3,"涌现与设计","注意：一个词是设计优于涌现的情形。",
     ["emergence","coordination","invisible-rules","local-vs-global"]],
    [3,"知识与无知","注意：一个词是无知被合理利用的情形。",
     ["blind-spot","counterfactual","abstraction-cost","signal-noise"]],
    [3,"制度的副作用","注意：一个词是制度正向作用的案例。",
     ["reversal-of-means","invisible-rules","legitimacy-sources","hierarchy-costs"]],
    [3,"效率的代价","注意：一个词是效率低下反而有益的情形。",
     ["bottleneck","necessary-waste","inversion-trap","delayed-effect"]],
    [3,"影响的路径","注意：一个词是直接影响而非间接。",
     ["contagion","second-order-effect","momentum","feedback-loop"]],
    [3,"现实的颗粒度","注意：一个词是高粒度损耗的情形。",
     ["granularity","map-territory","abstraction-cost","compressed-info"]],
    [3,"预测的局限","注意：一个词是预测可靠的条件。",
     ["counterfactual","selection-bias","path-dependency","blind-spot"]],
    [3,"沟通的损耗","注意：一个词是沟通无损传递的条件。",
     ["hierarchy-costs","translation-loss","context-collapse","signal-noise"]],
    [3,"竞争中的合作","注意：一个词是纯竞争优于合作的情形。",
     ["coordination","commons-dilemma","legitimacy-sources","emergence"]],
    [3,"惯性的用处","注意：一个词是克服惯性的情形。",
     ["path-dependency","momentum","sunk-cost-mirror","delayed-effect"]],
    [3,"设计与意图","注意：一个词是设计意图被误解的情形。",
     ["proxy-as-original","leaky-abstraction","context-collapse","reversal-of-means"]],
    [3,"不可见的结构","注意：一个词是结构可见的情形。",
     ["invisible-rules","hierarchy-costs","bottleneck","coordination"]],
    [3,"稀缺的思维","注意：一个词是丰裕思维的特征。",
     ["commons-dilemma","time-discount","invisible-cost","false-dichotomy"]],
    [3,"转化的损耗","注意：一个词是无损转化的条件。",
     ["translation-loss","abstraction-cost","map-territory","compressed-info"]],
    [3,"层级的失真","注意：一个词是层级扁平化的益处。",
     ["hierarchy-costs","path-dependency","legitimacy-sources","coordination"]],
    [3,"危机中的契机","注意：一个词是危机造成永久损害的情形。",
     ["threshold-states","inversion-trap","second-order-effect","delayed-effect"]],
    [3,"选择的代价","注意：一个词是选择多样性的益处。",
     ["false-dichotomy","path-dependency","anchor-bias","sunk-cost-mirror"]],
    [3,"信号的解读","注意：一个词是信号被正确解读的条件。",
     ["signal-noise","blind-spot","selection-bias","narrative-control"]],
    [3,"系统的自我修复","注意：一个词是系统无法自我修复的情形。",
     ["feedback-loop","necessary-waste","contagion","coordination"]],
    [3,"人与制度","注意：一个词是制度失灵时人的作用。",
     ["legitimacy-sources","invisible-rules","hierarchy-costs","reversal-of-means"]],
    [3,"身份的灵活性","注意：一个词是身份固化的危害。",
     ["identity-vs-role","context-collapse","path-dependency","invisible-rules"]],
]

# ── VALIDATE & MERGE ─────────────────────────────────────────────────────
errors = []

# Check new groups
all_new_words = set()
all_new_ids   = set()
for g in NEW_GROUPS:
    if g['id'] in existing_ids or g['id'] in all_new_ids:
        errors.append(f"Dup group id: {g['id']}")
    all_new_ids.add(g['id'])
    if len(g['words']) != 4 or len(set(g['words'])) != 4:
        errors.append(f"Bad words in group {g['id']}: {g['words']}")
    for w in g['words']:
        if w in all_new_words:
            errors.append(f"Cross-new-group dup word '{w}' in {g['id']}")
        all_new_words.add(w)

combined_bank = existing_bank + NEW_GROUPS
bank_by_id    = {g['id']: g for g in combined_bank}

# Check manifest entries
dist  = Counter(e['difficulty'] for e in existing_manifest)
need  = {1: max(0,100-dist[1]), 2: max(0,100-dist[2]), 3: max(0,100-dist[3])}

all_entries = D1[:need[1]] + D2[:need[2]] + D3[:need[3]]
for diff, theme, rh, gids in all_entries:
    if len(gids) != 4 or len(set(gids)) != 4:
        errors.append(f"Bad gids in '{theme}': {gids}")
    for gid in gids:
        if gid not in bank_by_id:
            errors.append(f"Missing group '{gid}' in puzzle '{theme}'")

if errors:
    print("ERRORS:")
    for e in errors: print(" ", e)
    raise SystemExit(1)

# ── WRITE OUTPUT ─────────────────────────────────────────────────────────
new_entries = [
    {"difficulty": diff, "theme": theme, "redHerring": rh, "groupIds": gids}
    for diff, theme, rh, gids in all_entries
]

data['textGroupBank']     = combined_bank
data['textPuzzleManifest']= existing_manifest + new_entries

final = Counter(e['difficulty'] for e in data['textPuzzleManifest'])
print(f"Existing bank: {len(existing_bank)}  New groups: {len(NEW_GROUPS)}")
print(f"Added puzzles: D1+{len(D1[:need[1]])}  D2+{len(D2[:need[2]])}  D3+{len(D3[:need[3]])}")
print(f"Final distribution: {dict(sorted(final.items()))}")
print(f"Total puzzles: {len(data['textPuzzleManifest'])}")

with open(ZH_PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("puzzle-data.json written OK")
